In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics.cluster import adjusted_rand_score as ARI
from sklearn.cluster import KMeans

In [2]:
# file = ['8clusters4x2.txt','4clusts.txt','4clusts_proximity.txt','6clusters3x2.txt','10d-4c-no0.dat','10d-4c-no1.dat',
#         '10d-4c-no2.dat','10d-4c-no3.dat','10d-4c-no4.dat','10d-4c-no5.dat','10d-4c-no6.dat','10d-4c-no7.dat','10d-4c-no8.dat',
#         '10d-4c-no9.dat','10d-10c-no0.dat','10d-10c-no1.dat','10d-10c-no2.dat','10d-10c-no3.dat','10d-10c-no4.dat','10d-10c-no5.dat',
#         '10d-10c-no6.dat','10d-10c-no7.dat','10d-10c-no8.dat','10d-10c-no9.dat','10d-20c-no0.dat','10d-20c-no1.dat','10d-20c-no2.dat',
#         '10d-20c-no3.dat','10d-20c-no4.dat','10d-20c-no5.dat','10d-20c-no6.dat','10d-20c-no7.dat','10d-20c-no8.dat','10d-20c-no9.dat',
#         '10d-40c-no0.dat','10d-40c-no1.dat','10d-40c-no2.dat','10d-40c-no3.dat','10d-40c-no4.dat','10d-40c-no5.dat','10d-40c-no6.dat',
#         '10d-40c-no7.dat','10d-40c-no8.dat','10d-40c-no9.dat', '15clusters5x3.txt', 'aggregation_edit.txt','banana_edit.txt','banknote.txt',
#         'brain_cancer.txt','breast-cancer-wisconsin.txt','ckplus_norm.txt','colon_cancer.txt','compound_edit.txt','D31_edit.txt','diffDensities_edit.txt',
#         'ecoli_v2.txt','examples1_edit.txt','flame_edit.txt','football_data.txt','gesture_phase_segmentation_a1_all.txt',
#         'grid5_edit.txt','human_activity_recognition_all.txt','iris_edit.txt','jaffe_norm.txt','jain_edit.txt','lotsOfClusters5_edit.txt',
#         'lung_cancer.txt','lymphoma_cancer.txt','movement_libras.data','pathbased_edit.txt','prostate_cancer.txt','R15.txt','sat.trn',
#         'seeds.txt','segment.dat','spambase.txt','spiral.txt','spiralsquare.txt','srbct_cancer.txt','s-set2.txt','wine.txt','yeast.txt']

In [3]:
# file = ['data_d20_c_10_no_0.txt','data_d20_c_10_no_1.txt','data_d20_c_10_no_2.txt','data_d20_c_10_no_3.txt','data_d20_c_10_no_4.txt',
#        'data_d20_c_20_no_0.txt','data_d20_c_20_no_1.txt','data_d20_c_20_no_2.txt','data_d20_c_20_no_3.txt','data_d20_c_20_no_4.txt',
#        'data_d20_c_35_no_0.txt','data_d20_c_35_no_1.txt','data_d20_c_35_no_2.txt','data_d20_c_35_no_3.txt','data_d20_c_35_no_4.txt',
#        'data_d20_c_50_no_0.txt','data_d20_c_50_no_1.txt','data_d20_c_50_no_2.txt','data_d20_c_50_no_3.txt','data_d20_c_50_no_4.txt',
#        'data_d35_c_10_no_0.txt','data_d35_c_10_no_1.txt','data_d35_c_10_no_2.txt','data_d35_c_10_no_3.txt','data_d35_c_10_no_4.txt',
#        'data_d35_c_20_no_0.txt','data_d35_c_20_no_1.txt','data_d35_c_20_no_2.txt','data_d35_c_20_no_3.txt','data_d35_c_20_no_4.txt',
#        'data_d35_c_35_no_0.txt','data_d35_c_35_no_1.txt','data_d35_c_35_no_2.txt','data_d35_c_35_no_3.txt','data_d35_c_35_no_4.txt',
#        'data_d35_c_50_no_0.txt','data_d35_c_50_no_1.txt','data_d35_c_50_no_2.txt','data_d35_c_50_no_3.txt','data_d35_c_50_no_4.txt',
#        'data_d50_c_10_no_0.txt','data_d50_c_10_no_1.txt','data_d50_c_10_no_2.txt','data_d50_c_10_no_3.txt','data_d50_c_10_no_4.txt',
#        'data_d50_c_20_no_0.txt','data_d50_c_20_no_1.txt','data_d50_c_20_no_2.txt','data_d50_c_20_no_3.txt','data_d50_c_20_no_4.txt',
#        'data_d50_c_35_no_0.txt','data_d50_c_35_no_1.txt','data_d50_c_35_no_2.txt','data_d50_c_35_no_3.txt','data_d50_c_35_no_4.txt',
#        'data_d50_c_50_no_0.txt','data_d50_c_50_no_1.txt','data_d50_c_50_no_2.txt','data_d50_c_50_no_3.txt','data_d50_c_50_no_4.txt']

In [4]:
cd E:/ISI/Datasets/datasets

E:\ISI\Datasets\datasets


In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics.cluster import adjusted_rand_score as ARI
from sklearn.cluster import KMeans
import math

def ret_cs(data,k,algo):
    cs_list = np.zeros((k, data.shape[1]))
    
    # Randomly initialise first center
    cs_list[0] = data[np.random.randint(1, data.shape[0])]
    
    #define some heuristic for m
    m = 5/(math.sqrt(data.shape[1])*math.log10(k+30))
    distance = np.zeros((k, data.shape[0]))
    mean = np.zeros(k)
    j = 0
    while j < k-1:
        distance[j,:] = np.linalg.norm((data - cs_list[j]), axis = 1)
        mean[j] = distance[j,:].mean()
        
        dist_set = distance[0:j+1] > (mean[0:j+1][:,None] * m)
        sdn = np.sum(dist_set, axis=0) == (j+1)
        if sdn.sum() > 0:
            index_set = np.where(sdn)[0]
            dist_mean = np.mean(distance[j,index_set])

            if algo == 'mean':
                closest_value = min(distance[j, index_set], key=lambda x:abs(x-dist_mean))
                index = index_set[np.where(distance[j, index_set] == closest_value)[0][0]]
                cs_list[j+1] = data[index]
            elif algo == 'max':
                index = index_set[np.where(distance[j, index_set] == np.max(distance[j, index_set]))[0][0]]
                cs_list[j+1] = data[index]
            elif algo == 'min':
                index = index_set[np.where(distance[j, index_set] == np.min(distance[j, index_set]))[0][0]]
                cs_list[j+1] = data[index]
            j = j + 1
        else:
            m = m - 0.025
        #print(m)
    return cs_list



In [11]:
file = ['8clusters4x2.txt','4clusts.txt','4clusts_proximity.txt','6clusters3x2.txt','10d-4c-no0.dat','10d-4c-no1.dat']
matrix = np.zeros((30,6))
matrix_mean_30runs = np.zeros((len(file),6))
no_of_runs = 30
for i in range(len(file)):
    dataset = str(file[i])
    print('DATASET:',dataset)
    a = np.loadtxt(file[i])
    k = len(np.unique(a[:,a.shape[1]-1]))
    print('k:',k)
    b = a[:,:a.shape[1]-1]
    for j in range(no_of_runs):
        cs_mean = ret_cs(b,k,'mean')
        cs_max = ret_cs(b,k,'max')
        #print(cs_mean)
        kmeans = KMeans(n_clusters=k, init = cs_mean, max_iter=100, n_init=1).fit(b)
        iterations = kmeans.n_iter_
        matrix[j,0] = iterations
        matrix[j,1] = ARI(kmeans.labels_, a[:,a.shape[1]-1])
        kmeans = KMeans(n_clusters=k, init = cs_max, max_iter=100, n_init=1).fit(b)
        iterations = kmeans.n_iter_
        matrix[j,2] = iterations
        matrix[j,3] = ARI(kmeans.labels_, a[:,a.shape[1]-1])
        kmeans = KMeans(n_clusters=k, max_iter=100, n_init=1).fit(b)
        iterations = kmeans.n_iter_
        matrix[j,4] = iterations
        matrix[j,5] = ARI(kmeans.labels_, a[:,a.shape[1]-1])
    #print(matrix)
    matrix_mean_30runs[i] = np.mean(matrix,axis=0)
    print(matrix_mean_30runs[i])
    print()

DATASET: 8clusters4x2.txt
k: 8
[5.1        0.9689457  5.3        0.96905191 5.3        0.96916702]

DATASET: 4clusts.txt
k: 4
[2. 1. 2. 1. 2. 1.]

DATASET: 4clusts_proximity.txt
k: 4
[5.         0.93453919 4.63333333 0.93453919 4.26666667 0.93453919]

DATASET: 6clusters3x2.txt
k: 6
[5.53333333 0.97215315 5.73333333 0.97215315 5.         0.97215315]

DATASET: 10d-4c-no0.dat
k: 4
[9.33333333 0.84237474 6.8        0.92876361 9.63333333 0.82858021]

DATASET: 10d-4c-no1.dat
k: 4
[4.56666667 0.96186385 5.23333333 0.97677033 8.33333333 0.97677033]



In [9]:
np.savetxt("results.csv", matrix_mean_30runs, delimiter=",")